  version: '3.1'

  services:
    app:
      depends_on:
        - database
      build: .
      ports:
        - 8085:8085

    database:
      image: postgres
      restart: always
      environment:
        - POSTGRES_USER=username
        - POSTGRES_PASSWORD=password
        - POSTGRES_DB=order-manager
      ports:
        - '5432:5432'
      volumes:
        - ./postgres-data:/var/lib/postgresql/data