  version: '3.1'

  services:
    app:
      depends_on:
        - database
        - mailhog
      build:
        context: .
      container_name: 'order_manager'
      environment:
        spring.datasource.url: 'jdbc:postgresql://database:5432/order-manager'
        spring.mail.host: 'mailhog'
      ports:
        - '8080:8080'

    database:
      image: postgres
      container_name: 'order_manager_database'
      restart: always
      environment:
        - POSTGRES_USER=username
        - POSTGRES_PASSWORD=password
        - POSTGRES_DB=order-manager
      ports:
        - '5432:5432'
      volumes:
        - postgres-data:/var/lib/postgresql/data

    mailhog:
      image: mailhog/mailhog
      container_name: 'mail_service'
      ports:
        - '1025:1025'
        - '8025:8025'

  volumes:
    postgres-data:
